### PR TITLE
I am very sorry - but for what ever reason 'let' is not working here

### PR DESCRIPTION
**Pull request by marq24**
I am very sorry - but for what ever reason here @ work the code with 'let' is not working here - giving me a n is undefined JS error...

So I just patched it to var and it is working again - looks like that there is also an issue on your current PROD :-/ *shame*

### CODE REVIEW

**Comment by TimMcCauley** [comment]
I fixed this already, it has got to do with traceur transpiling the code to ES5. Did you build and get this error or when exactly?

**Comment by marq24** [comment]
I made the change yesterday at home - and once I have been @ work now I started with a fresh system - and there on the initial builds I came across this error in the console... That n was undefined...

I thought this is the root cause of an error that is currently present on the production environment - where you get an leaflet error when you start to drag a point from the current route (to create a new 'via' entry):

`scripts.bb942bcae6b24062.js:12 Uncaught TypeError: Cannot read property 'segment_index' of undefined
    at e.<anonymous> (scripts.bb942bcae6b24062.js:12)
    at e.fire (vendor.9aac8a4a02d8449a.js:52)
    at e._onDragEnd (vendor.9aac8a4a02d8449a.js:53)
    at e.fire (vendor.9aac8a4a02d8449a.js:52)
    at e.finishDrag (vendor.9aac8a4a02d8449a.js:53)
    at e._onUp (vendor.9aac8a4a02d8449a.js:53)
    at r (vendor.9aac8a4a02d8449a.js:51)
    at j (vendor.9aac8a4a02d8449a.js:51)
    at HTMLDocument.n [as _leaflet_touchendtouchend165_334] (vendor.9aac8a4a02d8449a.js:51)`

I do not have this error locally with development branch... But I feel guilty for some reason.

I'll check the master as I type...

**Comment by marq24** [comment]
current master have:

`let i;
for (let i = 0, n = latlngs.length - 1; i < n; i++) {
`

what will cause the error mentioned above...

changing the code to

`for (var i = 0, n = latlngs.length - 1; i < n; i++) {`

works here locally for me (but double checking this right now)...

Development branch looks like this:

`let i;
for (i = 0, n = latlngs.length - 1; i < n; i++) {`

which is not working for me here locally - then I get again the 

`scripts.7fe463e87e4b8cb5.js:13 Uncaught ReferenceError: n is not defined
    at Scope.$scope.locateOnLineCopiedFromGeometryUtil (scripts.7fe463e87e4b8cb5.js:13)
    at Scope.$scope.addHoverPoint (scripts.7fe463e87e4b8cb5.js:13)
    at e.<anonymous> (scripts.7fe463e87e4b8cb5.js:13)
    at e.fire (vendor.02f8916eec2443ac.js:52)
    at e._fireDOMEvent (vendor.02f8916eec2443ac.js:52)
    at e._handleDOMEvent (vendor.02f8916eec2443ac.js:52)
    at HTMLElement.r (vendor.02f8916eec2443ac.js:51)`

error...

**Comment by marq24** [comment]
I have created to much confusion here locally - I'll need to fix my workplace and then I'll try it again

**Pull request closed without merging**
