### PR TITLE
Update hu-HU.json with new Hungarian translations

### PR DESCRIPTION
**Pull request by debyos**

### CODE REVIEW

**Comment by koebi** [comment]
Hey @debyos 

thank you very much for improving the hungarian translations of our old client.
However, the client has been deprecated in favor of [our new client](https://maps.openrouteservice.org/#/).

It would be very much appreciated if you could find the time to add a hungarian translation to our new client :))
You can find any information on contribution here:
https://github.com/GIScience/ors-map-client/#add-language

Best regards,
Jakob

**Comment by debyos** [comment]
Lieber Jakob,

das ist zu kompliziert für mich: ich bin ein Übersetzer der kaum programmieren kann.
So, if anyone creates me an English copy of all these required folders and files (code for Hungary is hu-hu) then I am keen to translate them but otherwise…
Danke!

Gábor

**Comment by koebi** [comment]
Hey Gábor,

that sounds very reasonable  :)

I have created a [starting point for an hungarian translation](https://github.com/GIScience/ors-map-client/pull/123) over in the new client's repo, let's continue any discussion over there :)

**Comment by TheGreatRefrigerator** [comment]
Included in https://github.com/GIScience/openrouteservice-app/commit/64c33210eb6dcc5ee38fc50ad079019051a01a1d

**Pull request closed without merging**
