### PR TITLE
Update it-IT.json

### PR DESCRIPTION
**Pull request by mircozorzo**
Only a little error.

### CODE REVIEW

**Comment by TimMcCauley** [comment]
@mircozorzo best of thanks - could you PR to development branch by any chance? Thanks a bunch!!

**Comment by mircozorzo** [comment]
Hi, thanks so much for the reply, I've done it in the spreadsheet.

Mirco

> @mircozorzo best of thanks - could you PR to development branch by any chance? Thanks a bunch!!

**Comment by TimMcCauley** [comment]
Okay, don't forget to create a new PR to development branch! ;)

**Comment by mircozorzo** [comment]
Thanks for the reply, I can't find this file in development branch.

it-IT.json
Excuse-me but I'm not very able to mange this elementary task.
Mirco

**Comment by tyrasd** [comment]
it's here @mircozorzo: https://github.com/GIScience/openrouteservice-app/blob/development/app/languages/it-IT.json

**Pull request closed without merging**
