### PR TITLE
add Docker file

### PR DESCRIPTION
**Pull request by stefanocudini**
I'm trying to add Dockerfile fot this app.
```bash
docker build -t test-ors-app
...
```
but receive this error building the image at bower install step..
```bash
Step 5/7 : RUN node_modules/bower/bin/bower install && 	cd bower_components/angularjs-slider && 	npm install && 	cd /ors-app
 ---> Running in 063ed551c681
/bin/sh: 1: node_modules/bower/bin/bower: not found
The command '/bin/sh -c node_modules/bower/bin/bower install && 	cd bower_components/angularjs-slider && 	npm install && 	cd /ors-app' returned a non-zero code: 127
```

maybe any of you know how to fix this?

it seems like a simple problem but I'm not very expert in docking

### CODE REVIEW

**Comment by tumluliu** [comment]
@stefanocudini (cc @TheGreatRefrigerator) Take `ubuntu:18.04` as the base image is not the best option to dockerize ors-app. I would suggest you to checkout the official tutorial from nodejs of how to build an image for a node application: https://nodejs.org/de/docs/guides/nodejs-docker-webapp/

back to your question: as the message shows clearly, `bower` is not properly installed to proceed the following steps.

Apart from that, your dockerfile has a couple of anti-best-practice issues, e.g. multiple `RUN` commands will generate multiple layers unnecessarily, lack of metadata, could be split into multi-stage to avoid mixing building and running, etc.. There are tons of Dockerfile guidelines online. Please refer to them and you will definitely get your Dockerfile improved. From the top of Google's results:
- https://www.docker.com/blog/intro-guide-to-dockerfile-best-practices/
- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

This one will be helpful as well although it's about Docker container instead of Docker image: https://developers.redhat.com/blog/2016/02/24/10-things-to-avoid-in-docker-containers/

last but not least: your commit message also can be better. `add Docker` doesn't sound good for me.

**Comment by stefanocudini** [comment]
the motivation to contribute to ORS has just passed me

**Comment by TimMcCauley** [comment]
@tumluliu 👋 ;-) valid points!

@stefanocudini you can get it running quickly if you 

`RUN npm install -g bower`

**Comment by stefanocudini** [comment]
> @tumluliu  ;-) valid points!
> 
> @stefanocudini you can get it running quickly if you
> 
> `RUN npm install -g bower`

thanks for the constructive suggestions


@tumluliu 
https://opensource.guide/best-practices/#keep-the-conversation-friendly

> 
If you don’t want to accept a contribution:
* **Thank them** for their contribution
* **Explain why it doesn’t fit** into the scope of the project, and offer clear suggestions for improvement, if you’re able. Be kind, but firm.
* **Link to relevant documentation**, if you have it. If you notice repeated requests for things you don’t want to accept, add them into your documentation to avoid repeating yourself.
* **Close the request**
>

**Comment by nilsnolde** [comment]
I agree @stefanocudini. It's not only what you say, it's how you say it. @tumluliu might be some valid points, but it's a bit cheeky to carelessly piss off potential contributors on projects you don't work on since ages. That's generally my job :wink:

How about this: @stefanocudini you work on the Dockerfile a little more (it's really worth it to dig a little more into how Docker works, you'll love it. Hint: multi-staging images between build and prod really makes sense to keep the final image size & footprint down) and @tumluliu can review your PR with some constructive comments, you both shake hands and be happy about a good deed done for the week?

**Comment by tumluliu** [comment]
Hi @TimMcCauley, hi @nilsnolde , sorry for bringing you such inconveniences after I left the project for longer than a century. Wish you guys and @TheGreatRefrigerator are doing great. 

@stefanocudini Some points from my side:
1. As Nils mentioned, I am not working in ORS project now. All my comments are solely my personal options, which have nothing to do with ORS team. Please don't treat any of those craps as the official response, neither a signal of approval nor decline
2. I personally am always happy to see any contribution from anyone to ORS, and always appreciate the contributor's efforts. But I could not thank you on behalf of ORS team because of 1
3. My comments are only for the commit, from a normal DevOps engineer's point of view. The purpose is nothing simpler than to have a working and elegant Dockerfile for ors-app, which can help ORS be better. If they made you unhappy, I feel very sorry about that. 
4. I hope that in the future, (pls @TimMcCauley @nilsnolde  correct me if I'm wrong), before pressing the PR creation button, it would be super awesome for people to make sure they are really well-prepared for the PR by checking at least: 1). if the contribution guidelines in README have been read through; 2). if the corresponding best practices like coding style, performance and vulnerability considerations, etc. have been applied as much as possible; 3). if the commits comply with git best practices and git-flow. All these checkings will considerably save other people's time

---- the end of non-tech part ----

w.r.t the Dockerfile, my first batch of suggestions:

1. Update the base image to one of the official nodejs images
2. Add a metadata section
3. Combine `RUN`s to avoid unnecessary extra layers
4. Separate the image building and running into two stages

**Comment by nilsnolde** [comment]
Thanks @tumluliu, that sounds good to me. Our "contribution guidelines" on this particular project are not very detailed unfortunately. In any case, I agree, PRs should be well prepared generally. Nevertheless, not everyone wanting to contribute to FOSS underwent a thorough (if self-taught) education in the giant dev universe and we should do our best to gently nudge them in the right direction. Just like you did in your last comment:)

**Comment by TheGreatRefrigerator** [comment]
Wow, one day not at work and activity is going through the roof!
I should do this way more often.

@stefanocudini thanks a lot for wanting to contribute!
First thing: if you are still willing to contribute, please reopen the PR based on development.
Lu has some points regarding commit message & coding style/best practice, but it doesn't have to be perfect.
In the contrary: We are happy for people to contribute at all in the first place!

If you won't be working on this anymore, i will take this over.
To avoid us doing the same work, it would be great if you leave a short notice on your desicion.

@tumluliu Heeeeey, nice to hear from you! I hope you are doning fine ^^. I was really surprised when you replied all of a sudden. I would be interested to know why this pull took your interest? My guess is because of docker :D
I know that you wanted to help, but as nils already mentioned: that was a bit direct 😅 
Oh and btw. Tim is also not working here anymore, i was also surprised that he answered.

@nilsnolde, @TimMcCauley thanks for your input guys. 
You could comment more often, haha

Cya all

**Comment by nilsnolde** [comment]
What's the status here @stefanocudini ? Should we close or will you try to improve the Dockerfile?

**Comment by stefanocudini** [comment]
@nilsnolde why I'm view "Merging is blocked"? :-/

however my version of Dockefile is tested and it works for me.
to apply it to my specific case I mounted an external **Gruntfile.js volume** so that I can configure the services

surely you can write in a better way (as I said I am not a Docker expert but I tried to share my work)

it was a long job to make this combination of docker commands work as the exact instructions of the normal installation on the readme did not work in the docker image (I refer to the various npm / bower installs)

**Comment by nilsnolde** [comment]
Well, we requested quite a few changes, none of them has been addressed as far as I can see:

- too many RUN statements
- no LABEL like `maintainer`
- `Ubuntu` base image is not ideal, e.g. `node:12.13.1-alpine` or similar is better
- also there's no need to `git clone` the repository: you're already inside it with Docker

It's noble to put in so much time. But a contribution also needs to meet a certain level of quality. I'm happy to offer a little more guidance, but in this state we can't merge. If it works for you, that's fine then. And if you don't want to improve anymore, maybe someone else will pick it up at some point again.

**Comment by stefanocudini** [comment]
I'm Sorry, the context in which I use ors-app is not generic but specific to my project (without source included and I need ubuntu in the next changes)

Ok, I hope my Dockerfile:
https://github.com/stefanocudini/openrouteservice-app/blob/master/Dockerfile
will be useful to someone who wants to make a PR with more generalized code in the future

**Comment by stefanocudini** [comment]
@nilsnolde this new PR may be is better:
https://github.com/GIScience/openrouteservice-app/pull/345

**Pull request closed without merging**
